name: Estudo
description: Template para organizar tarefas e anotações de estudo
title: "[ESTUDO]: "
labels: "study"
body:
  - type: markdown
    attributes:
      value: "## Tópico de Estudo"
  - type: textarea
    attributes:
      label: Descreva qual assunto você está estudando.
      placeholder: "Ex: Fluxo de Trabalho com Git e GitHub"
  - type: markdown
    attributes:
      value: "## Objetivo"
  - type: textarea
    attributes:
      label: O que você deseja aprender ou resolver?
  - type: checkboxes
    id: prioridade
    attributes:
      label: Prioridade
      options:
        - label: Muito alta
        - label: Alta
        - label: Média
        - label: Baixa
  - type: checkboxes
    id: progresso
    attributes:
      label: Progresso
      options:
        - label: Iniciado
        - label: Em andamento
        - label: Concluído
  - type: textarea
    id: notas
    attributes:
      label: Notas
      description: Anotações adicionais sobre o estudo.
