# Nome do Workflow
name: Deploy Hugo site to Pages

on:
  # Roda quando um push é feito na branch `main`
  push:
    branches:
      - main

  # Permite que você rode este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões necessárias para o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      
      # Adicionado: Instala as dependências do Node.js (PostCSS)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        # CORREÇÃO: Roda o build a partir da raiz do projeto
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # CORREÇÃO: O Hugo gera o site na pasta 'docs' (definido no hugo.toml)
          path: ./docs

  # Job de Deploy (não precisa de alteração)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4