# deploy.yml

name: Deploy Hugo site to Pages

on:
  # Roda quando um push é feito na branch "gh-pages"
  push:
    branches:
      - gh-pages

  # Permite que você rode este workflow manualmente pela aba Actions
  workflow_dispatch:

# Permissões do GITHUB_TOKEN para o deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de Build - constrói o site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Essencial para baixar o tema

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload da pasta 'public' que o Hugo gerou
          path: ./public

  # Job de Deploy - publica o site
  deploy:
    runs-on: ubuntu-latest
    needs: build # Este job só roda depois que o job 'build' terminar com sucesso
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Usa o artefato gerado no passo anterior