# Nome do Workflow
name: Deploy Hugo site to Pages

on:
  # Roda quando um push é feito na branch `main`
  push:
    branches:
      - main
    # Roda apenas se houverem mudanças na pasta docs/
    paths:
      - 'docs/**'

  # Permite que você rode este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões necessárias para o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          # A CORREÇÃO: Usar a versão estendida do Hugo
          extended: true

      - name: Build
        # Roda o build a partir da pasta 'docs'. O site será gerado em uma pasta 'public' na raiz.
        run: hugo --minify --source docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Define o caminho para a pasta que será publicada
          path: ./public

  # Job de Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # O job de deploy só roda depois que o de build for concluído com sucesso
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
