name: Build and Deploy Hugo site to gh-pages

on:
  push:
    branches:
      - documentacao
  workflow_dispatch:

# Permissão para o robô ter poder de escrita no repositório
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Token que dá permissão para a Action fazer o push
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # A pasta que contém o site pronto (padrão do Hugo quando não especificamos publishDir)
          publish_dir: ./public
