# Nome do Workflow
name: Deploy Hugo site to Pages

# Gatilho: rodar quando houver um push na branch 'main'
on:
  push:
    branches:
      - main # Mude para 'master' se for o caso do seu repositório
  # Permite que você rode este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões para o GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea, cancelando as mais antigas.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        # O comando --source aponta para a pasta do seu site Hugo
        # O site será gerado na pasta 'public' na raiz do projeto
        run: hugo --minify --source docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/public

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
