name: Deploy Hugo site to gh-pages

on:
  # Roda quando um push é feito na branch `documentacao`
  push:
    branches:
      - documentacao

  # Permite rodar manualmente
  workflow_dispatch:

# Define as permissões
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # O token é necessário para permitir que a Action faça um push para a branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # A pasta que contém o site gerado (padrão do Hugo)
          publish_dir: ./public
          # O nome da branch de destino
          publish_branch: gh-pages
